# permissions for end users to edit clusterorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterorder-editor-role
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders/status
  verbs:
  - get
