# permissions for end users to view clusterorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterorder-viewer-role
rules:
- apiGroups:
  - osac.openshift.io
  resources:
  - clusterorders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osac.openshift.io
  resources:
  - clusterorders/status
  verbs:
  - get
