# This rule is not used by the project osac-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to osac.openshift.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: computeinstance-viewer-role
rules:
- apiGroups:
  - osac.openshift.io
  resources:
  - computeinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osac.openshift.io
  resources:
  - computeinstances/status
  verbs:
  - get
