# This rule is not used by the project osac-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to view resources within the cloudkit.openshift.io.
# This role is intended for users who need to monitor and view these resources
# but should not be able to modify them.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: hostpool-viewer-role
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - hostpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - hostpools/status
  verbs:
  - get
