apiVersion: cloudkit.openshift.io/v1alpha1
kind: HostPool
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: hostpool-sample
spec:
  hostSets:
  - hostClass: fc430
    size: 3
  - hostClass: fc830
    size: 1
