apiVersion: cloudkit.openshift.io/v1alpha1
kind: ComputeInstance
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: computeinstance-sample
spec:
  templateID: "sample_template"
