## Append samples of your project ##
resources:
- cloudkit_v1alpha1_clusterorder.yaml
- cloudkit_v1alpha1_host.yaml
- cloudkit_v1alpha1_hostpool.yaml
- cloudkit_v1alpha1_computeinstance.yaml
- cloudkit_v1alpha1_tenant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
