## Append samples of your project ##
resources:
- osac_v1alpha1_clusterorder.yaml
- osac_v1alpha1_hostpool.yaml
- osac_v1alpha1_computeinstance.yaml
- osac_v1alpha1_tenant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
