apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hypershift.openshift.io_hostedclusters.yaml
- hypershift.openshift.io_nodepools.yaml
- k8s.ovn.org_userdefinednetworks.yaml
- kubevirt.io_virtualmachineinstances.yaml
